version: '3.8'

services:
  new-api:
    image: ${REGISTRY:-crpi-appxm8pdgvw49jw2.cn-hangzhou.personal.cr.aliyuncs.com/blueming3}/new-api:${TAG:-latest}
    container_name: new-api
    restart: unless-stopped
    command: --log-dir /app/logs
    ports:
      - "${NEW_API_PORT:-8999}:3000"
    volumes:
      - ${DATA_DIR:-./data}:/data
      - ${LOGS_DIR:-./logs}:/app/logs
    environment:
      - SQL_DSN=${SQL_DSN}
      - REDIS_CONN_STRING=${REDIS_CONN_STRING}
      - TZ=${TZ:-Asia/Shanghai}
      - ERROR_LOG_ENABLED=${ERROR_LOG_ENABLED:-true}
      - SESSION_SECRET=${SESSION_SECRET}
      - INITIAL_ROOT_TOKEN=${INITIAL_ROOT_TOKEN}
      - STREAMING_TIMEOUT=${STREAMING_TIMEOUT:-300}
      - GENERATE_DEFAULT_TOKEN=${GENERATE_DEFAULT_TOKEN:-true}
    depends_on:
      - redis
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: ${REGISTRY:-crpi-appxm8pdgvw49jw2.cn-hangzhou.personal.cr.aliyuncs.com/blueming3}/redis:${REDIS_TAG:-latest}
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  mysql:
    image: ${REGISTRY:-crpi-appxm8pdgvw49jw2.cn-hangzhou.personal.cr.aliyuncs.com/blueming3}/mysql:${MYSQL_TAG:-latest}
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-new-api}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"

volumes:
  mysql_data:
